from pathlib import Path
p=Path('tools/audio-editor/index.html');s=p.read_text(encoding='utf-8')
a=s.index("  const audioFilesInput");b=s.index('  // Initialize home button',a)
s=s[:a]+s[b:];s=s.replace('</body>', '<script src="../../assets/audio-editor.js"></script>\n</body>')
p.write_text(s,encoding='utf-8')
p=Path('tools/image-sharp-resize/index.html');s=p.read_text(encoding='utf-8').replace('https://unpkg.com/pica@5.0.0/dist/pica.min.js','../../assets/vendor/pica.min.js')
s=s.replace("    const img = new Image();\n    img.src = URL.createObjectURL(file);\n    img.onload = async () => {", "    const img = new Image();\n    const sourceUrl = URL.createObjectURL(file);\n    btnResize.disabled = true;\n    img.onload = async () => {\n      try {")
s=s.replace('const offscreen = new OffscreenCanvas(finalWidth, FinalHeight);','const offscreen = new OffscreenCanvas(finalWidth, finalHeight);')
s=s.replace('const offscreen = new OffscreenCanvas(finalWidth, finalHeight);', "const offscreen = document.createElement('canvas');\n      offscreen.width = finalWidth; offscreen.height = finalHeight;")
s=s.replace("unsharpAmount: 80,", "filter: 'lanczos3',\n              unsharpAmount: 80,")
s=s.replace("offscreen.convertToBlob({type: file.type}).then(blob => {", "const blob = await new Promise(resolve => offscreen.toBlob(resolve, ['image/png','image/jpeg','image/webp'].includes(file.type) ? file.type : 'image/png'));\n      if (!blob) throw new Error('Image export failed');\n      {\n        if (resultUrl) URL.revokeObjectURL(resultUrl);")
s=s.replace("const url = URL.createObjectURL(blob);", "const url = resultUrl = URL.createObjectURL(blob);")
s=s.replace("const ext = file.name.substring(file.name.lastIndexOf('.'));", "const ext = { 'image/png': '.png', 'image/jpeg': '.jpg', 'image/webp': '.webp' }[blob.type] || '.png';")
s=s.replace("          URL.revokeObjectURL(url);",'')
s=s.replace("      }).catch(err => {", "      }\n      } catch (err) {")
s=s.replace("      });\n    };\n    img.onerror", "      } finally { URL.revokeObjectURL(sourceUrl); btnResize.disabled = false; }\n    };\n    img.onerror")
s=s.replace("    img.onerror = () => {", "    img.onerror = () => {\n      URL.revokeObjectURL(sourceUrl); btnResize.disabled = false;")
s=s.replace("  // Initialize home button", "  // Initialize home button")
s=s.replace("    };\n  });\n\n  // Initialize", "    };\n    img.src = sourceUrl;\n  });\n\n  // Initialize")
s=s.replace("  btnResize.addEventListener", "  let resultUrl;\n  window.addEventListener('pagehide', () => { if (resultUrl) URL.revokeObjectURL(resultUrl); });\n  btnResize.addEventListener")
p.write_text(s,encoding='utf-8')
