from pathlib import Path
root = Path(__file__).resolve().parent.parent
for p in [root/'index.html', *root.glob('tools/*/index.html')]:
    s = p.read_text(encoding='utf-8')
    prefix = '../../' if p.parent != root else ''
    s = s.replace('<script src="'+prefix+'assets/shared.js"></script>', '<script src="'+prefix+'assets/shared.js"></script>\n<link rel="stylesheet" href="'+prefix+'assets/shared.css">')
    s = s.replace('--accent:#0969da;', '--accent:#0969da; --accent-hover:#0860ca;').replace('--accent:#58a6ff;', '--accent:#58a6ff; --accent-hover:#79b8ff;')
    s = s.replace("if(dict[key] !== undefined) el.textContent = dict[key];", "if(dict[key] !== undefined) {\n        if (/^placeholder/i.test(key) && el.matches('textarea, input')) el.placeholder = dict[key];\n        else el.textContent = dict[key];\n      }")
    p.write_text(s, encoding='utf-8')

def edit(name, fn):
    p=root/'tools'/name/'index.html'; p.write_text(fn(p.read_text(encoding='utf-8')), encoding='utf-8')
edit('image-editor', lambda s: s.replace("function applyTheme(light){", "let currentLang = SharedSettings.getLang();\nfunction applyTheme(light){").replace("let currentLang = 'zh';\n",'').replace("document.documentElement.classList.toggle('light-theme', light);", "document.documentElement.classList.toggle('light-theme', light);\n  document.documentElement.dataset.theme = light ? 'light' : 'dark';"))
edit('ai-cooldown', lambda s:s.replace("getElementById('langToggle')", "getElementById('localeToggle')"))
edit('csv-converter', lambda s:s.replace('https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papa.min.js','../../assets/vendor/papaparse.min.js').replace('margin-bottom:400px; overflow-y:auto;', 'margin-bottom:24px; overflow-y:auto;').replace("complete: function(results) {", "complete: function(results) {\n          if (results.errors.length) {\n            jsonOutput.value = '';\n            hintCsv2json.textContent = results.errors.map(err => err.message).join('; ');\n            btnDownloadJson.onclick = null;\n            return;\n          }"))
edit('hash-calculator', lambda s:s.replace('<script src="../../assets/shared.js"></script>', '<script src="../../assets/shared.js"></script>\n<script src="../../assets/vendor/md5.min.js"></script>').replace("const hashBuffer = await crypto.subtle.digest(hashAlgorithm.value, dataToHash);", "const hashBuffer = hashAlgorithm.value === 'MD5' ? null : await crypto.subtle.digest(hashAlgorithm.value, dataToHash);").replace("const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');", "const hashHex = hashAlgorithm.value === 'MD5' ? md5(dataToHash) : hashArray.map(b => b.toString(16).padStart(2, '0')).join('');").replace("btnCopy.addEventListener('click', () => {", "btnCopy.addEventListener('click', async () => {").replace("btnCopyHash.addEventListener('click', () => {", "btnCopyHash.addEventListener('click', async () => {").replace("resultHash.select();\n    document.execCommand('copy');", "if (!resultHash.textContent) return;\n    try { await SharedSettings.copyText(resultHash.textContent); }\n    catch (e) { alert(lang === 'zh' ? '複製失敗，請手動選取結果' : 'Copy failed; please select the result manually'); return; }"))
edit('base64-converter', lambda s:s.replace('btoa(String.fromCharCode(...new Uint8Array(e.target.result)))', 'SharedSettings.bytesToBase64(new Uint8Array(e.target.result))').replace('btoa(encodeTextInput.value)', 'SharedSettings.bytesToBase64(new TextEncoder().encode(encodeTextInput.value))').replace('decodeOutput.innerHTML = `<pre>${textOutput}</pre>`;', "decodeOutput.replaceChildren();\n        const pre = document.createElement('pre');\n        pre.textContent = textOutput;\n        decodeOutput.appendChild(pre);").replace('<button class="btn" id="btnDecodeDownload" data-i18n="btnDownload">下載結果</button>', '<a class="btn" id="btnDecodeDownload" data-i18n="btnDownload" style="display:none">下載結果</a>').replace("const url = URL.createObjectURL(blob);\n\n        decodeOutput", "if (btnDecodeDownload.href) URL.revokeObjectURL(btnDecodeDownload.href);\n        const url = URL.createObjectURL(blob);\n\n        decodeOutput").replace("new TextDecoder('utf-8')", "new TextDecoder('utf-8', {fatal:true})"))
